In [1]:
# Initial... will continue tomorrow.
import getpass
import sqlalchemy
import pandas as pd

In [2]:
user = getpass.getpass()

 ····

In [3]:
pwd = getpass.getpass()

 ·······························

In [5]:
DB_URIfix='mysql+pymysql://'+user+':'+pwd+'@35.197.16.55/wiki'+'?charset=utf8mb4'
engine = sqlalchemy.create_engine(DB_URIfix)

### Input

In [8]:
# input: URL
# take the last part of it:
url_last_part = 'Know_Nothing' # Example

### Graphical Similarity

In [10]:
SQL_graphical = """
SELECT *
FROM wiki.Clickstream 
WHERE `From` = '"""+url_last_part+"""';
"""

df1 = pd.read_sql(SQL_graphical, engine)
df1

,Snapshot,From,To,RelationType,Count
0,202001,Know_Nothing,Thaddeus_Stevens,link,125
1,202001,Know_Nothing,Constitutional_Union_Party_(United_States),link,1980
2,202001,Know_Nothing,1854_and_1855_United_States_House_of_Represent...,link,137
3,202001,Know_Nothing,Anti-Catholicism,link,268
4,202001,Know_Nothing,Anthony_Kennedy_(Maryland),link,95
...,...,...,...,...,...
93,202001,Know_Nothing,J._Neely_Johnson,link,41
94,202001,Know_Nothing,American_nationalism,link,89
95,202001,Know_Nothing,Noah_Gordon_(novelist),link,28
96,202001,Know_Nothing,Flag_of_the_United_States,other,34
97,202001,Know_Nothing,1852_United_States_presidential_election,link,14

### Semantic Similarity

In [11]:
# need to use nearest neighbours on this. Will runtime be ridiculous? 
# Maybe the query results should be stored in memory upon flask start-time.
SQL_semantic = """
SELECT * FROM wiki.Summary limit 400;
"""

df2 = pd.read_sql(SQL_semantic, engine)
df2

,Snapshot,Article,Article Vector Centroid,TextStat Fleisch Reading Difficulty,Degree,Betweenness Centrality,Clicks in month,Article Length
0,202001,India,[-0.53758313 -0.05517562 -0.43962049 0.404986...,-1461.53,3877.0,0.256531,2.025850,0.159862
1,202001,Philippines,[-0.60068248 -0.06057958 -0.39165653 0.307496...,-1950.08,1597.0,0.179688,0.854837,0.220767
2,202001,Arabic,[-0.1975094 -0.27144646 -0.47610304 0.185288...,-5315.82,1320.0,0.069198,0.337495,0.581369
3,202001,London,[-0.69324299 -0.25935533 -0.38372183 0.562229...,-913.43,1544.0,0.134051,0.747275,0.099687
4,202001,Christianity,[-7.02245254e-01 -3.85773260e-01 -3.79399775e-...,-1720.69,1137.0,0.136424,0.439041,0.193817
...,...,...,...,...,...,...,...,...
395,202001,Discrete_Fourier_transform,[-0.38670883 0.33157421 -0.74825473 0.543223...,-1895.27,0.0,0.000000,0.000000,0.203708
396,202001,Hahn–Banach_theorem,[-0.44622238 0.3039546 -0.77093171 0.649713...,-744.26,0.0,0.000000,0.000000,0.079875
397,202001,Stimulus–response_model,[-0.59772091 0.15007167 -0.56645496 0.449830...,-61.85,0.0,0.000000,0.000000,0.004694
398,202001,Reincarnation,[-0.63068973 -0.30048558 -0.36555517 0.464161...,-1906.44,203.0,0.052929,0.131557,0.216587
399,202001,Charles_Sanders_Peirce,[-7.24723388e-01 -1.56054358e-01 -5.02696135e-...,-2492.43,0.0,0.000000,0.000000,0.283706